kind: Deployment
apiVersion: apps/v1
metadata:
  name: group15
  namespace: group15
  labels:
    app: group15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group15
  template:
    metadata:
      labels:
        app: group15
    spec:
      containers:
        - name: group15
          image: [your_image_name:latest]
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: group15
  namespace: group03
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: group15
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: group15 route
  namespace: group03
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`15.web.dops.tech`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: group15
          port: 80
  tls:
    certResolver: myresolver
